# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a5323c881aa7397fa6812d7aeaf0e44b3f2c2171781736b93a0cc5894ed1b3f54a245f85af00d47d4ad96934662eda273de54c2c7219861e221aba0fb787e9b

test:
  secret_key_base: cdec8e5b492ec8721dd6303e27f9d52966c7d70c526cb1622b1bd09eff81f91f46bd4daa9bb021219cf1e3b47749787048e78ad3c84bfe725a39af784ada2ae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
